keys:
  - &ibuki age1n7f9ldphjqs0ylzw7ftag0pc988gd3jtneyejmjp8r0gcyuh3pmsr48rx2
  - &nixmox age1a0anpkz7xteshdkdycayxssqw6e9vus6z8yetcl6ycnrz4yfkexqlf9fxm
creation_rules:
  - path_regex: secrets/common/system\.yaml
    key_groups:
      - age:
        - *ibuki
        - *nixmox
